parameters:
  phpflo_bundle.builder_class: 'PhpFlo\PhpFloBundle\Flow\NetworkBuilder'
  phpflo_bundle.component.builder_class: 'PhpFlo\Builder\ComponentDiFinder'
  phpflo_bundle.network_class: 'PhpFlo\Network'
  phpflo_bundle.traceable_network_class: 'PhpFlo\TraceableNetwork'
  phpflo_bundle.default_logger_class: 'PhpFlo\Logger\SimpleFile'

services:
