parameters:

services:
  asm_phpflo:
    class: Asm\PhpFloBundle\Flow\Builder
    lazy: true
    arguments:
      - '@asm_phpflo.component_registry'
      - '%kernel.root_dir%'

  asm_phpflo.component_registry:
    class: Asm\PhpFloBundle\Flow\ComponentRegistry
    lazy: true
