parameters:

services:
  asm_phpflo:
    class: Asm\PhpFloBundle\Flow\NetworkBuilder
    lazy: true
    arguments:
      - '@asm_phpflo.component_registry'
      - '%kernel.root_dir%'

  asm_phpflo.component_registry:
    class: PhpFlo\ComponentRegistry
    lazy: true
