parameters:

services:
  phpflo:
    class: PhpFlo\PhpFloBundle\Flow\NetworkBuilder
    lazy: true
    arguments:
      - '@phpflo.component_registry'
      - '%kernel.root_dir%'

  phpflo.component_registry:
    class: PhpFlo\ComponentRegistry
    lazy: true
